version: "3"
services:
  postgres:
    image: postgres:12
    container_name: dating-api-postgres
    hostname: postgres
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresGOLANG
      POSTGRES_DB: dating-api
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - public
    restart: unless-stopped

volumes:
  postgres-data:
networks:
  public:
    external:
      name: public
